"""ODEP CLI entry point."""
from __future__ import annotations
import os, sys
from datetime import datetime
from typing import Optional
import click
from odep.cli.commands.config import config_group
from odep.cli.commands.dq import dq
from odep.cli.commands.local import local
from odep.cli.commands.template import template
from odep.config import OdepConfig
from odep.factory import get_metadata_adapter, get_orchestrator_adapter
from odep.sdk.deploy import deploy_pipeline

@click.group()
def odep():
    """Open Data Engineering Platform CLI."""
    pass

@odep.command()
@click.argument("project_name", default="my-data-platform")
@click.option("--engine", default="duckdb", type=click.Choice(["duckdb","spark","trino","flink","dbt","clickhouse","metamind"]), show_default=True)
def init(project_name, engine):
    """Scaffold a new ODEP project directory."""
    os.makedirs(project_name, exist_ok=True)
    open(os.path.join(project_name, ".odep.env"), "w").write(f"ODEP_METADATA__ENGINE=openmeta\nODEP_ORCHESTRATION__ENGINE=airflow\nODEP_EXECUTION__DEFAULT_ENGINE={engine}\n")
    open(os.path.join(project_name, "odep.yaml"), "w").write(f"project_name: {project_name}\nenvironment: local\nmetadata:\n  engine: openmeta\norchestration:\n  engine: airflow\nexecution:\n  default_engine: {engine}\n")
    open(os.path.join(project_name, "docker-compose.yml"), "w").write('# Generated by odep init\nversion: "3.9"\nservices: {}\n')
    click.echo(f"✅ Initialized project '{project_name}' with engine={engine}")

@odep.command()
@click.argument("path")
@click.option("--env", default="local", show_default=True)
@click.option("--schedule", default=None)
def deploy(path, env, schedule):
    """Deploy a pipeline to the configured orchestrator."""
    try:
        job_id = deploy_pipeline(path, env, schedule, config=OdepConfig())
        click.echo(f"✅ Deployed pipeline as job {job_id}")
    except Exception as e:
        click.echo(f"❌ Deploy failed: {e}"); sys.exit(1)

@odep.command()
@click.argument("job_id")
@click.option("--backfill", is_flag=True, default=False)
@click.option("--start", default=None)
@click.option("--end", default=None)
def run(job_id, backfill, start, end):
    """Trigger a pipeline run or backfill."""
    try:
        config = OdepConfig()
        orch = get_orchestrator_adapter(config.orchestration.engine, config.orchestration)
        if backfill:
            ids = orch.backfill(job_id, datetime.fromisoformat(start), datetime.fromisoformat(end))
            click.echo(f"✅ Enqueued {len(ids)} backfill runs")
        else:
            click.echo(f"✅ Triggered run {orch.trigger_job(job_id)}")
    except Exception as e:
        click.echo(f"❌ Run failed: {e}"); sys.exit(1)

@odep.command()
@click.argument("run_id")
@click.option("--tail", default=100, type=int, show_default=True)
def logs(run_id, tail):
    """Fetch logs for a pipeline run."""
    try:
        config = OdepConfig()
        orch = get_orchestrator_adapter(config.orchestration.engine, config.orchestration)
        for line in orch.get_logs(run_id, tail=tail): click.echo(line)
    except Exception as e:
        click.echo(f"❌ Failed to fetch logs: {e}"); sys.exit(1)

@odep.command()
@click.argument("path")
@click.option("--suite", default="", help="Path to a .yaml suite file.")
@click.option("--llm-evaluate", is_flag=True, default=False)
def test(path, suite, llm_evaluate):
    """Run a data quality suite against a data file or SQL query."""
    from pathlib import Path as P
    suite_path = suite or (str(P(path).with_suffix(".yaml")) if P(path).with_suffix(".yaml").exists() else "")
    if not suite_path:
        click.echo("⚠️  No suite file found. Use --suite or run: odep dq generate <data> -o rules.yaml"); sys.exit(1)
    try:
        from odep.cli.commands.dq import _load_data, _print_results
        from odep.dq.runner import run_quality_suite
        from odep.dq.serializer import load_suite
        from odep.exceptions import QualityGateFailure
        suite_obj = load_suite(suite_path)
        df = _load_data(path)
        click.echo(f"🧪 Running suite '{suite_obj.name}' ({len(suite_obj.rules)} rules)...")
        result = None
        try:
            result = run_quality_suite(suite_obj, df, raise_on_blocking=True)
        except QualityGateFailure as e:
            _print_results(result); click.echo(f"\n❌ Quality gate failed: {e}"); sys.exit(1)
        _print_results(result)
        if llm_evaluate:
            from odep.dq.llm_advisor import LLMAdvisor
            click.echo("\n🤖 LLM evaluation:\n" + LLMAdvisor.from_config().evaluate_results(result))
        if result.has_blocking_failures: sys.exit(1)
    except Exception as e:
        click.echo(f"❌ Test failed: {e}"); sys.exit(1)

@odep.command()
@click.argument("urn")
def lineage(urn):
    """Show upstream lineage for a dataset URN."""
    try:
        config = OdepConfig()
        adapter = get_metadata_adapter(config.metadata.engine, config.metadata)
        graph = adapter.get_full_upstream(urn)
        edges = [e for el in graph.values() for e in el]
        if not edges: click.echo(f"No upstream lineage found for {urn}"); return
        click.echo(f"Upstream lineage for: {urn}")
        for e in edges: click.echo(f"{e.source_urn} → {e.target_urn}")
    except Exception as e:
        click.echo(f"❌ {e}"); sys.exit(1)

@odep.command()
def cost():
    """Estimate cost for a pipeline run."""
    click.echo("💰 Cost estimation requires a running job handle. Use 'get_metrics(job_handle)' via the SDK.")

odep.add_command(local)
odep.add_command(template)
odep.add_command(config_group, name="config")
odep.add_command(dq)

if __name__ == "__main__":
    odep()
