-- MetaMind Migration 011 — AI Synthesis Layer Tables
-- Applies after: 010_routing_policies.sql

-- Enable uuid extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------
-- mm_synthesized_rules — rules generated by the AI synthesis engine
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mm_synthesized_rules (
    rule_id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(64) NOT NULL REFERENCES mm_tenants(tenant_id),
    name            VARCHAR(256) NOT NULL,
    description     TEXT,
    rule_type       VARCHAR(64) NOT NULL
                    CHECK (rule_type IN ('join_order','pushdown','engine_affinity','agg_pushdown')),
    condition       JSONB NOT NULL DEFAULT '{}',
    transformation  JSONB NOT NULL DEFAULT '{}',
    confidence      NUMERIC(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    support_count   INTEGER DEFAULT 0,
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    last_fired_at   TIMESTAMPTZ,
    fire_count      INTEGER DEFAULT 0,
    retired_at      TIMESTAMPTZ,
    UNIQUE(tenant_id, name)
);

-- -----------------------------------------------------------------------
-- mm_synthesis_cycles — execution history for synthesis runs
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mm_synthesis_cycles (
    cycle_id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        VARCHAR(64) NOT NULL,
    rules_generated  INTEGER DEFAULT 0,
    rules_retired    INTEGER DEFAULT 0,
    retrained        BOOLEAN DEFAULT FALSE,
    mae_before       NUMERIC(10,4),
    mae_after        NUMERIC(10,4),
    cycle_duration_ms INTEGER,
    completed_at     TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------
-- mm_training_samples — individual ML cost-model training records
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mm_training_samples (
    sample_id   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id   VARCHAR(64) NOT NULL,
    features    JSONB NOT NULL DEFAULT '{}',
    runtime_ms  NUMERIC(12,3) NOT NULL,
    engine      VARCHAR(64) NOT NULL,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_synth_rules_tenant
    ON mm_synthesized_rules(tenant_id);

CREATE INDEX IF NOT EXISTS idx_synth_rules_active
    ON mm_synthesized_rules(is_active, tenant_id)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_synth_cycles_tenant
    ON mm_synthesis_cycles(tenant_id, completed_at DESC);

CREATE INDEX IF NOT EXISTS idx_training_samples_tenant
    ON mm_training_samples(tenant_id, recorded_at DESC);

-- Backfill join_count / agg_count / filter_count columns on mm_query_logs
-- if they don't already exist (added by workload profiler)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'mm_query_logs' AND column_name = 'join_count'
    ) THEN
        ALTER TABLE mm_query_logs
            ADD COLUMN join_count    INTEGER DEFAULT 0,
            ADD COLUMN agg_count     INTEGER DEFAULT 0,
            ADD COLUMN filter_count  INTEGER DEFAULT 0,
            ADD COLUMN subquery_depth INTEGER DEFAULT 0,
            ADD COLUMN sql_fingerprint VARCHAR(32),
            ADD COLUMN tables_accessed JSONB;
    END IF;
END
$$;
